import React from "react";
import Head from "next/head";

import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>CS CAMP 15</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div className="flex min-h-screen flex-col">
        {/* <Navbar /> */}
        <Navbar />
        <div className="app-main relative flex grow flex-col">{children}</div>
        {/* <Footer /> */}
        <Footer />
      </div>

      <style jsx scoped>{`
        .app-main {
          padding-top: var(--navbar-height);
        }
      `}</style>
    </>
  );
};

export default Layout;
